package_assets: off
template_function: _.template
javascripts:
  app:
    - public/javascripts/underscore-min.js
    - public/javascripts/backbone-min.js
    - public/javascripts/mustache.js
    - public/javascripts/application.js
    - public/javascripts/models/*.js
    - public/javascripts/**/*.js

stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
    - public/stylesheets/ie.css